export enum AuditEvent {
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    LOGIN_FAILED = "LOGIN_FAILED",
    LOGOUT = "LOGOUT",
    PASSWORD_CHANGED = "PASSWORD_CHANGED",
    PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED",
    EMAIL_VERIFIED = "EMAIL_VERIFIED",
    VERIFICATION_EMAIL_SENT = "VERIFICATION_EMAIL_SENT",
    ACCOUNT_CREATED = "ACCOUNT_CREATED",
    SESSION_REVOKED = "SESSION_REVOKED",
    TOKEN_REUSE_DETECTED = "TOKEN_REUSE_DETECTED",
}