export const AUTH_CONSTANTS = {
  ACCESS_TOKEN_EXPIRY: "15m",
  REFRESH_TOKEN_EXPIRY: "30d",
  MAX_LOGIN_ATTEMPTS: 5,
  MAX_REGISTER_ATTEMPTS: 5,
  MAX_FORGOT_PASSWORD_ATTEMPTS: 3,
  EMAIL_COOLDOWN_SECONDS: 60
} as const;